# Generated by Django 3.2 on 2021-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211108_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='domicilio',
            field=models.ManyToManyField(to='api.Domicilio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='domicilio',
            field=models.ManyToManyField(to='api.Domicilio'),
        ),
        migrations.AlterField(
            model_name='radiologo',
            name='domicilio',
            field=models.ManyToManyField(to='api.Domicilio'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='domicilio',
            field=models.ManyToManyField(to='api.Domicilio'),
        ),
    ]
