# Generated by Django 3.2 on 2021-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211108_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
