# Generated by Django 3.2 on 2021-11-09 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_domicilio_fecha_hasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='radiografia',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='radiografia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.radiografia'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
    ]
