# Generated by Django 3.2 on 2021-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211108_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name': 'Resultado'},
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='resultado',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='codigo_estudio',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='estudio',
            field=models.CharField(default='Radiografia de torax', max_length=100),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medico'),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AddField(
            model_name='radiologo',
            name='numero_matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='legajo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numero_matricula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='radiologo',
            name='dni',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='radiologo',
            name='legajo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='dni',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='legajo',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
