# Generated by Django 3.2 on 2021-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211109_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiografia',
            name='placa',
            field=models.ImageField(upload_to='media'),
        ),
    ]
