# Generated by Django 3.2 on 2021-11-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_radiografia_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologo',
            name='numero_matricula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
