# Generated by Django 3.2 on 2021-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_radiologo_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiografia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
