# Generated by Django 3.2 on 2021-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_radiografia_codigo_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
